[package]
name = "rust_lrn"
version = "1.0.0"
authors = ["Janith Harendra <janithh884@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
term = "0.7.0"